from django.urls import path,include
from .import views

urlpatterns = [
    path('',views.homepage,name='homepage'),
    path('loginpage',views.loginpage,name='loginpage'),
    path('signuppage',views.signuppage,name='signuppage'),
    path('usercreate',views.usercreate,name='usercreate'),
    path('adminhome',views.adminhome,name='adminhome'),
    path('userlog',views.userlog,name='userlog'),
    path('categoryadd',views.categoryadd,name='categoryadd'),
    path('addcategory',views.addcategory,name='addcategory'),
    path('managecategory',views.managecategory,name='managecategory'),
    path('deletecategory/<int:cd>',views.deletecategory,name='deletecategory'),
    path('productadd',views.productadd,name='productadd'),
    path('addproduct',views.addproduct,name='addproduct'),
    path('manageproduct',views.manageproduct,name='manageproduct'),
    path('deleteproduct/<int:pd>',views.deleteproduct,name='deleteproduct'),
    path('managecustomer',views.managecustomer,name='managecustomer'),
    path('deletecustomer/<int:cd>',views.deletecustomer,name='deletecustomer'),
    path('customerhome',views.customerhome,name='customerhome'),
    path('logout',views.logout,name='logout'),
    path('customerprofile/<int:cp>/', views.customerprofile,name='customerprofile'),
    path('editcustomer/<int:ec>',views.editcustomer,name='editcustomer'),
    path('itemcard/<int:cp>',views.itemcard, name='itemcard'),  
    # path('view_cart',views.view_cart, name='view_cart'),
    # path('add_to_cart/<int:prod>', views.add_to_cart, name='add_to_cart'),
    # # path('cart/', views.view_cart, name='cart_view'),  
    # path('add_to_cart/<int:prod>/',views.add_to_cart, name='add_to_cart'),
    # path('remove_from_cart/<int:itm>', views.remove_from_cart, name='remove_from_cart'),
    # # path('buyproduct/<int:pro>', views.buyproduct, name='buyproduct'),
    # # path('buy_porodcut/<int:prdct>', views.buy_product, name='buy_product'),
    # path('about',views.about, name='about'),
    # path('editproduct/<int:ep>',views.editproduct,name='editproduct'),
    #  path('cart/', views.cartview, name='cart'),  # Cart view
    # path('buyproduct/<int:pro>/', views.buyproduct, name='buyproduct'), 
    # path('buy_product/<int:prdct>/', views.buy_product, name='buy_product'),

    path('cart/', views.cartview, name='cart'), 
    path('view_cart/', views.cartview, name='view_cart'),  
    path('add_to_cart/<int:prod>/', views.add_to_cart, name='add_to_cart'),  
    path('remove_from_cart/<int:itm>/', views.remove_from_cart, name='remove_from_cart'),  
    path('buyproduct/<int:pro>/', views.buyproduct, name='buyproduct'),  
    path('buy_product/<int:prdct>/', views.buy_product, name='buy_product'),  
    path('editproduct/<int:ep>/', views.editproduct, name='editproduct'), 
    path('about/', views.about, name='about'), 
]